language: csharp
sudo: false # faster builds
dist: xenial
notifications:
  email: false
env:
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
before_install:
  - git lfs pull
install:
  - dotnet restore
mono: none
dotnet: 8.0
script:
  - dotnet restore
  - cd tests/
  - dotnet test
